### ISSUE TITLE
feat: project milestones

### ISSUE THREAD

**Issue by mikewuu** [homie-gg/homie#12]
- [ ] Ability to define a list of milestones
- [ ] Show milestone contribution
- [ ] Show milestone alignment
- [ ] Show summary of PRs analyzed for period
