### ISSUE TITLE
feat(PR): confirm checklist

### ISSUE THREAD

**Issue by mikewuu** [homie-gg/homie#130]
PRs have checklists. Devs don't read checklists. Homie can read for them :)

This task is to add a feature where users can define checks that a PR must pass.

eg:

- [ ] include X label
- [ ] add new test for new behavior
- [ ] add test for bugs
- [ ] add link to task
