### ISSUE TITLE
feat: add task tracking

### ISSUE THREAD

**Issue by mikewuu** [homie-gg/homie#37]
Currently Homie only tracks PRs. 

This task is to add the ability to track tasks, so that Homie can help find tasks for devs.

### Implementation

- [x] Create schema
- [x] Handle saving GitHub issues
- [x] Import tasks on setup
- [x] Save contributor
- [x] Handle tasks updates from GitHub
- [x] Add sort algorithm
- [x] Add tools
- [x] Handle task updates from Homie
- [ ] ~~Add ability to send daily tasks summaries~~ https://github.com/homie-gg/homie/issues/35
### Task schema 

- name
- description
- created_at
- updated_at
- status:
  - open
  - done
 - is_assigned (bool)
 - url
 - due_date (optional)
 - type
   - feature
   - bug fix
   - maintenance
   - planning

### Task priority 

Homie will automatically classify a task and assign a priority

- p0 = critical bug
- p1 = important bug /feature
- p2 = feature or minor bug
- p3 = minor ux improvement or maintenance

### Requirements

- [ ] ~~Able to prioritize task: "Homie please prioritize this task"~~ https://github.com/homie-gg/homie/issues/39
- [x] Priority sort algo should take into account task age
- [x] Save task on create 
- [x] Sync task on updates

### Task actions

- [x] find available task
- [x] list completed tasks
- [x] get tasks person X is working on
- [x] Able to assign task to person Y
- [ ] ~~get task of type~~ https://github.com/homie-gg/homie/issues/51
- [x] ability to mark task as complete

### Integrations

- [x] GitHub Issues
- [ ] ~~Trello~~ https://github.com/homie-gg/homie/issues/53
- [ ] ~~Gitlab Issues~~ https://github.com/homie-gg/homie/issues/52

### Test

- [x] Issue create -> create tasks
- [x] Import tasks on setup
- [x] Issue update -> edit task
- [x] issue close -> close task
- [x] Assigned -> creates assignment in homie
- [x] unassign - remove assignment in homie
- [x] deleted -> deletes task in homie
- [x] re-opened -> marks task as open again
- [x] Assign task to user
- [x] Find what contributor is doing
- [x] Mark task as done
- [x] Find completed tasks
- [x] List available tasks
